spring:
  application:
    name: service-C
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8507/
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
message: service-C dev mode