spring:
  application:
    name: service-A
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8507/
  security:
    user:
      name: test
      password: 123
jwt:
  signingSecret: EatktOhVUNCzUTql02t63a7UBIykErln1mQ1D0uyoS4KmS2RJJReerLZ9Ib2phWn
  encryptionSecret: R5ORfLhGOpHyTdHQ1UiRuWROSMyUyOm4
  header: jwtToken
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
message: service-A dev mode